### ISSUE TITLE
Invalid OAuth2 redict_url

### ISSUE THREAD

**Issue by EnythNet** [peterhanania/Pogy-Old#16]
So I have problems with the Invalid OAuth2 redict_url. I configured all Redirects & it's still coming with this error.
![image](https://user-images.githubusercontent.com/80833026/131355119-1b3e948d-e9d2-4efe-8e74-927d6d1424a5.png)
![image](https://user-images.githubusercontent.com/80833026/131355496-decd3cfa-3cba-4f4d-bbf6-054ee5f45faf.png)

Here is my config for this dashboard: 

module.exports = {
 "verification": "",
 "description": "hi",
 "domain": "REMOVED FOR SECURITY REASONS",
 "google_analitics": "",
 "token": process.env.TOKEN,
 "https":"https://",
 "port":"8080",
 "client_id":"REMOVED FOR SECURITY REASONS",
 "secret":"REMOVED FOR SECURITY REASONS"
}

---------------

Maybe I added wrong Redirects?

**Comment by peterhanania** [comment]
1- Make sure your domain is correct in the config.js file. Example **http://localhost:5000**

2- Make sure the domain doesn't have a **/** at the end, it affects. (**http://google.com** instead of  **http://google.com/**)

If it still doesn't work open a ticket in Pogy's support server and we will help you from there.

**Comment by EnythNet** [comment]
Alr, I will make a ticket as it doesn't works.
